name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        worksp  ace: [backend, frontend
    steps:
      - uses: actions/checkout@v4
          
      - run: npm install -w ${{ matrix.workspace }}
      - run: npm --workspace ${{ matrix.workspace }} run lint
      - run: npm --workspace ${{ matrix.workspace }} run test --if-present
